import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const josefin = Josefin_Sans({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});





// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      
      className={`${josefin.className} h-full antialiased light`}
      data-theme="light"
      suppressHydrationWarning
    >
      
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900">
        
        <Navbar/>
        
        <main className="grow">{children}</main>
        
        
      </body>
    </html>
  );
}
